/*
--- Day 7: Laboratories ---
You thank the cephalopods for the help and exit the trash compactor, finding yourself in the familiar halls of a North Pole research wing.

Based on the large sign that says "teleporter hub", they seem to be researching teleportation; you can't help but try it for yourself and step onto the large yellow teleporter pad.

Suddenly, you find yourself in an unfamiliar room! The room has no doors; the only way out is the teleporter. Unfortunately, the teleporter seems to be leaking magic smoke.

Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment lying around. After connecting one of the diagnostic tools, it helpfully displays error code 0H-N0, which apparently means that there's an issue with one of the tachyon manifolds.

You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters the manifold at the location marked S; tachyon beams always move downward. Tachyon beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.

For example:

.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:

.......S.......
.......|.......
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
At that point, the original beam stops, and two new beams are emitted from the splitter:

.......S.......
.......|.......
......|^|......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
Those beams continue downward until they reach more splitters:

.......S.......
.......|.......
......|^|......
......|.|......
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
At this point, the two splitters create a total of only three tachyon beams, since they are both dumping tachyons into the same place between them:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
This process continues until all of the tachyon beams reach a splitter or exit the manifold:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
.....|.|.|.....
....|^|^|^|....
....|.|.|.|....
...|^|^|||^|...
...|.|.|||.|...
..|^|^|||^|^|..
..|.|.|||.|.|..
.|^|||^||.||^|.
.|.|||.||.||.|.
|^|^|^|^|^|||^|
|.|.|.|.|.|||.|
To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of 21 times.

Analyze your manifold diagram. How many times will the beam be split?
*/

import { _readInput } from '../../lib.js';

const START = 'S';
const SPLITTER = '^';
const TACHYON = '|';
const EMPTY = '.';

const getS = (line) => line.findIndex((el) => el === START);
const getTree = (fileInput) => _readInput(fileInput).map((l) => l.split(''));

const day07 = (tree) => {
  let count = 0;
  const treeLength = tree.length;
  tree[1][getS(tree[0])] = TACHYON;

  for (let row = 2; row < treeLength - 1; row++) {
    const rowLength = tree[row].length;

    for (let col = 0; col < rowLength; col++) {
      const chr = tree[row][col];

      if (chr === TACHYON && tree[row + 1][col] === EMPTY)
        tree[row + 1][col] = TACHYON;

      if (chr === SPLITTER) {
        if (tree[row - 1][col] === TACHYON) {
          tree[row + 1][col - 1] = TACHYON;
          tree[row + 1][col + 1] = TACHYON;
          count++;
        }
      }
    }
  }

  //for (let i = 0; i < treeLength; i++) console.log(tree[i].join(''));

  return count;
};

// --------------------------------------------------------

const day07Two = (fileInput) => {
  const data = _readInput(fileInput);

  return data;
};

//const fileInput = './2025/day07/example.txt'; // 21 -
const fileInput = './2025/day07/input.txt'; // 1524 -

console.log(day07(getTree(fileInput)));
//console.log(day07Two(fileInput));
